type:
        "xnexp"
max_probability:
        type: lognormal
        s: 0.5 
        loc: 0.0
        scale: 1. 
norm_time:       
        type: constant
        value: 1.
asymptomatic_infectious_factor:
        type: constant
        value: 1.
mild_infectious_factor:
        type: constant
        value: 1.
