hospitalisation:
    start_time: 1000-01-01
    end_time: 9999-01-01

severe_symptoms_stay_home:
    start_time: 1000-01-01
    end_time: 9999-01-01

quarantine:
    1:
        n_days: 7 # for the symptomatic person
        n_days_household: 14 # for the housemates
        compliance: 0.5 
        household_compliance: 0.2
        start_time: 2020-03-16 
        end_time: 2020-03-24 
    2:
        n_days: 7 # for the symptomatic person
        n_days_household: 14 # for the housemates
        compliance: 0.95 # for the symptomatic individual - needs to be checked
        household_compliance: 0.9
        start_time: 2020-03-24
        end_time: 2021-07-04

shielding:
    1:
        min_age: 70
        compliance: 0.2
        start_time: 2020-03-16 
        end_time: 2020-03-24
    2:
        min_age: 70
        compliance: 0.7
        start_time: 2020-03-24
        end_time: 2020-08-01

    # CIRCUIT BREAKER
    3:
        min_age: 70
        compliance: 0.7
        start_time: 2020-11-07
        end_time: 2020-11-21


close_companies:
    1:
        start_time: 2020-03-16
        end_time: 2020-03-20
        full_closure: False 
        avoid_work_probability: 0.20 # prob of avoiding workplace if still working (YouGov)
        furlough_probability: 0.04 # prob of being furloughed (Statista)
        key_probability: 0.22 # prob of being a key worker (ONS)
    2:
        start_time: 2020-03-20
        end_time: 2020-03-27
        full_closure: False 
        avoid_work_probability: 0.29
        furlough_probability: 0.04
        key_probability: 0.22
    3:
        start_time: 2020-03-27
        end_time: 2020-04-17
        full_closure: False 
        avoid_work_probability: 0.38
        furlough_probability: 0.04
        key_probability: 0.22
    4:
        start_time: 2020-04-17
        end_time: 2020-05-01
        full_closure: False 
        avoid_work_probability: 0.36
        furlough_probability: 0.1
        key_probability: 0.22
    5:
        start_time: 2020-05-01
        end_time: 2020-05-15
        full_closure: False 
        avoid_work_probability: 0.35
        furlough_probability: 0.25
        key_probability: 0.22
    6:
        start_time: 2020-05-15
        end_time: 2020-06-16
        full_closure: False 
        avoid_work_probability: 0.31
        furlough_probability: 0.30
        key_probability: 0.22
    7:
        start_time: 2020-06-16
        end_time: 2020-07-12
        full_closure: False 
        avoid_work_probability: 0.25
        furlough_probability: 0.33
        key_probability: 0.22
    8:
        start_time: 2020-07-12
        end_time: 2020-07-26
        full_closure: False 
        avoid_work_probability: 0.21
        furlough_probability: 0.34
        key_probability: 0.22
    9:
        start_time: 2020-07-26
        end_time: 2020-08-07
        full_closure: False 
        avoid_work_probability: 0.20
        furlough_probability: 0.34
        key_probability: 0.22
    10:
        start_time: 2020-08-07
        end_time: 2020-08-12
        full_closure: False 
        avoid_work_probability: 0.20
        furlough_probability: 0.34
        key_probability: 0.22
    11:
        start_time: 2020-08-12
        end_time: 2020-08-25
        full_closure: False 
        avoid_work_probability: 0.18
        furlough_probability: 0.34
        key_probability: 0.22
    12:
        start_time: 2020-08-25
        end_time: 2020-09-09
        full_closure: False 
        avoid_work_probability: 0.15
        furlough_probability: 0.34
        key_probability: 0.22
    13:
        start_time: 2020-09-09
        #end_time: 2020-09-17
        #end_time: 2020-12-01
        end_time: 2020-11-07
        full_closure: False 
        avoid_work_probability: 0.135
        furlough_probability: 0.34
        key_probability: 0.22

    # CIRCUIT BREAKER
    14:
        start_time: 2020-11-07
        end_time: 2020-11-24
        full_closure: False 
        avoid_work_probability: 0.38
        furlough_probability: 0.34
        key_probability: 0.22
    15:
        start_time: 2020-11-24
        end_time: 2021-12-01
        full_closure: False 
        avoid_work_probability: 0.135
        furlough_probability: 0.34
        key_probability: 0.22


social_distancing:
    1: 
        start_time: 2020-03-16
        end_time: 2020-03-24 
        beta_factors:
            box: 0.875
            pub: 0.875
            grocery: 0.875
            cinema: 0.875
            commute_unit: 0.875
            commute_city_unit: 0.875
            hospital: 0.875
            care_home: 0.875
            company: 0.875
            school: 0.875
            household: 1.0
            university: 0.875

    2:
        start_time: 2020-03-24
        end_time: 2020-07-04 
        beta_factors:
            box: 0.75
            pub: 0.75
            grocery: 0.75
            cinema: 0.75
            commute_unit: 0.75
            commute_city_unit: 0.75
            hospital: 0.75
            care_home: 0.75
            company: 0.75
            school: 0.75
            household: 1.0
            university: 0.75
    3:
        start_time: 2020-07-04 
        #end_time: 2020-12-10
        end_time: 2020-11-07
        beta_factors:
            box: 0.875
            pub: 0.875
            grocery: 0.875
            cinema: 0.875
            commute_unit: 0.875
            commute_city_unit: 0.875
            hospital: 0.875
            care_home: 0.875
            company: 0.875
            school: 0.875
            household: 1.0
            university: 0.875

    # CIRCUIT BREAKER
    4:
        start_time: 2020-11-07
        end_time: 2020-11-24
        beta_factors:
            box: 0.75
            pub: 0.75
            grocery: 0.75
            cinema: 0.75
            commute_unit: 0.75
            commute_city_unit: 0.75
            hospital: 0.75
            care_home: 0.75
            company: 0.75
            school: 0.75
            household: 1.0
            university: 0.75
    5:
        start_time: 2020-11-24
        end_time: 2021-12-10
        beta_factors:
            box: 0.875
            pub: 0.875
            grocery: 0.875
            cinema: 0.875
            commute_unit: 0.875
            commute_city_unit: 0.875
            hospital: 0.875
            care_home: 0.875
            company: 0.875
            school: 0.875
            household: 1.0
            university: 0.875

mask_wearing:
    1: 
        start_time: 2020-03-27
        end_time: 2020-04-24
        compliance: 0.09 # overall mask wearing compliance (YouGov)
        beta_factor: 0.5 # overall beta reducion if mask wearing
        mask_probabilities: # given a mask is work, probability of where it is worn
            box: 1.
            pub: 0.
            grocery: 0.5
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    2: 
        start_time: 2020-04-24
        end_time: 2020-05-21
        compliance: 0.17
        beta_factor: 0.5
        mask_probabilities:
            box: 1.
            pub: 0.
            grocery: 0.5
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    3: 
        start_time: 2020-05-21
        end_time: 2020-06-16
        compliance: 0.23
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 0.5
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    4: 
        start_time: 2020-06-16
        end_time: 2020-06-25
        compliance: 0.29
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 0.5
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    5: 
        start_time: 2020-06-25
        end_time: 2020-07-12
        compliance: 0.35
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 0.5
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    6: 
        start_time: 2020-07-12
        end_time: 2020-07-24
        compliance: 0.48
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 0.5
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    7: 
        start_time: 2020-07-24
        end_time: 2020-07-26
        compliance: 0.48
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 1.
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    8: 
        start_time: 2020-07-26
        end_time: 2020-07-31
        compliance: 0.63
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 1.
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    9: 
        start_time: 2020-07-31
        end_time: 2020-08-07
        compliance: 0.67
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 1.
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    10: 
        start_time: 2020-08-07
        end_time: 2020-08-12
        compliance: 0.70
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 1.
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5

    11: 
        start_time: 2020-08-12
        end_time: 2020-08-25
        compliance: 0.745
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 1.
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    12: 
        start_time: 2020-08-25
        end_time: 2020-09-08
        compliance: 0.725
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 1.
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    13: 
        start_time: 2020-09-08
        #end_time: 2020-09-16
        end_time: 2021-12-01
        compliance: 0.735
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 1.
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5

close_leisure_venue:
    1:
        start_time: 2020-03-21
        end_time: 2020-07-04 
        venues_to_close: ['pub', 'cinema', 'care_home_visit']

    # CIRCUIT BREAKER
    2:
        start_time: 2020-11-07
        end_time: 2020-11-24
        venues_to_close: ['pub', 'cinema', 'care_home_visit']

change_leisure_probability:
    1:
        start_time: 2020-03-24
        end_time: 2020-07-04
        leisure_activities_probabilities:
            household_visits:
                men: 
                    0-64: 0.50
                    65-100: 0.25
                women: 
                    0-64: 0.50
                    65-100: 0.25
            care_home_visits:
                men:
                    0-100: 0.05
                women:
                    0-100: 0.05

    2:
        start_time: 2020-07-04
        end_time: 2020-07-11
        leisure_activities_probabilities:
            pubs:
                men:
                    18-65: 0.256
                    65-100: 0.170
                women:
                    18-65: 0.256
                    65-100: 0.170

    3:
        start_time: 2020-07-11
        end_time: 2020-07-18
        leisure_activities_probabilities:
            pubs:
                men:
                    18-65: 0.402
                    65-100: 0.268
                women:
                    18-65: 0.402
                    65-100: 0.268

    4:
        start_time: 2020-07-18
        end_time: 2020-07-25
        leisure_activities_probabilities:
            pubs:
                men:
                    18-65: 0.548
                    65-100: 0.366
                women:
                    18-65: 0.548
                    65-100: 0.366

    5:
        start_time: 2020-07-25
        end_time: 2020-08-01
        leisure_activities_probabilities:
            pubs:
                men:
                    18-65: 0.695
                    65-100: 0.463
                women:
                    18-65: 0.695
                    65-100: 0.463

    6:
        start_time: 2020-08-01
        end_time: 2020-08-08
        leisure_activities_probabilities:
            pubs:
                men:
                    18-65: 0.841
                    65-100: 0.561
                women:
                    18-65: 0.841
                    65-100: 0.561

    7:
        start_time: 2020-08-08
        end_time: 2020-08-15
        leisure_activities_probabilities:
            pubs:
                men:
                    18-65: 0.988
                    65-100: 0.659
                women:
                    18-65: 0.988
                    65-100: 0.659

    8:
        start_time: 2020-08-15
        end_time: 2020-08-22
        leisure_activities_probabilities:
            pubs:
                men:
                    18-65: 1.13
                    65-100: 0.756
                women:
                    18-65: 1.13
                    65-100: 0.756

    9:
        start_time: 2020-08-22
        end_time: 2020-08-29
        leisure_activities_probabilities:
            pubs:
                men:
                    18-65: 1.28
                    65-100: 0.854
                women:
                    18-65: 1.28
                    65-100: 0.854

    10:
        start_time: 2020-08-29
        end_time: 2020-08-31
        leisure_activities_probabilities:
            pubs:
                men:
                    18-65: 1.38
                    65-100: 0.917
                women:
                    18-65: 1.38
                    65-100: 0.917

    # CIRCUIT BREAKER

    11:
        start_time: 2020-11-07
        end_time: 2020-11-24
        leisure_activities_probabilities:
            household_visits:
                men: 
                    0-64: 0.50
                    65-100: 0.25
                women: 
                    0-64: 0.50
                    65-100: 0.25
            care_home_visits:
                men:
                    0-100: 0.05
                women:
                    0-100: 0.05


close_schools:
    1:
        start_time: 2020-03-20
        end_time: 2020-06-01
        years_to_close: all
        full_closure: False
    2:
        start_time: 2020-06-01
        end_time: 2020-06-11
        years_to_close: [0,1,2,7,8,9,12,13,14,15,16,17,18,19]
        attending_compliance: 0.125
        full_closure: False
    3:
        start_time: 2020-06-11
        end_time: 2020-06-18
        years_to_close: [0,1,2,7,8,9,12,13,14,15,16,17,18,19]
        attending_compliance: 0.195
        full_closure: False
    4:
        start_time: 2020-06-18
        end_time: 2020-06-25
        years_to_close: [0,1,2,7,8,9,12,13,14,15,16,17,18,19]
        attending_compliance: 0.253
        full_closure: False
    5:
        start_time: 2020-06-25
        end_time: 2020-07-02
        years_to_close: [0,1,2,7,8,9,12,13,14,15,16,17,18,19]
        attending_compliance: 0.312
        full_closure: False
    6:
        start_time: 2020-07-02
        end_time: 2020-07-16
        years_to_close: [0,1,2,7,8,9,12,13,14,15,16,17,18,19]
        attending_compliance: 0.37 
        full_closure: False
    7:
        start_time: 2020-07-16
        end_time: 2020-09-01
        years_to_close: all
        full_closure: False
    8:
        start_time: 2020-10-26
        end_time: 2020-10-31
        years_to_close: all
        full_closure: False

close_universities:
    start_time: 2020-03-20
    end_time: 2020-09-28