age_range: [8,13]      # numbers correspond to age groups defined by NOMIS dataset.
sector: 'Q'            # NOMIS name convention
sub_sector:
  nurse:
    sector_id: 2231    # NOMIS name convention
  doctor:
    sector_id: 2211    # NOMIS name convention
