kid_max_age : 17
student_min_age : 18
student_max_age : 25
old_min_age : 65
old_max_age : 99
adult_min_age : 18
adult_max_age : 64
young_adult_min_age : 18
young_adult_max_age : 35
max_age_to_be_parent : 64
max_household_size : 8
allowed_household_compositions : [
    "1 0 >=0 1 0",
    ">=2 0 >=0 1 0",
    "1 0 >=0 2 0",
    ">=2 0 >=0 2 0",
    "1 0 >=0 >=1 >=0",
    ">=2 0 >=0 >=1 >=0",
    "0 0 0 0 >=2",
    "0 >=1 0 0 0",
    "0 0 0 0 1",
    "0 0 0 0 2",
    "0 0 0 1 0",
    "0 0 0 2 0",
    "0 0 >=1 1 0",
    "0 0 >=1 2 0",
    "0 0 >=0 >=0 >=0",
    ">=0 >=0 >=0 >=0 >=0",
]
contact_matrices:
  contacts: [[1.20, 1.69, 1.69, 1.69], [1.27, 1.34, 1.47, 1.47], [1.27, 1.30, 1.34, 1.34], [1.27, 1.30, 1.34, 2.00]]
  proportion_physical: [[0.79, 0.7, 0.7, 0.7], [0.7, 0.34, 0.4, 0.62], [0.7, 0.4, 0.62, 0.62], [0.7, 0.4, 0.62, 0.45]]
 
