male:
  0-5:
    cardiovascular: 0.001
    chronic_kidney: 0.001
    chronic respiratory: 0.009
    chronic_liver disease: 0.002
    diabetes_mellitus: 0.
    cancers_w_direct_immunosuppression: 0.004
    cancers_w_possible_immunosuppression: 0.001
    HIV/AIDS: 0.
    tuberculosis: 0.
    chronic_neurological: 0.004
    sickle_cell: 0.
  5-9:
    cardiovascular: 0.002
    chronic_kidney: 0.002
    chronic respiratory: 0.016
    chronic_liver disease: 0.002
    diabetes_mellitus: 0.001
    cancers_w_direct_immunosuppression: 0.006
    cancers_w_possible_immunosuppression: 0.
    HIV/AIDS: 0.
    tuberculosis: 0.005 
    chronic_neurological: 0.
    sickle_cell: 0.
  10-14:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  15-19:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  20-24:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  25-29:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  30-34:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  35-39:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  40-44:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  45-49:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  50-54:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  55-59:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  60-64:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  65-69:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  70-74:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  75-79:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  80-84:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  85-89:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  90-94:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  95-100:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.

female:
  0-5:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell:
    sickle_cell: 0.
  5-9:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  10-14:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  15-19:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  20-24:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  25-29:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  30-34:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  35-39:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  40-44:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  45-49:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  50-54:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  55-59:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  60-64:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  65-69:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  70-74:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  75-79:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  80-84:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  85-89:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  90-94:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.
  95-100:
    cardiovascular:
    chronic_kidney:
    chronic respiratory:
    chronic_liver disease:
    diabetes_mellitus:
    cancers_w_direct_immunosuppression:
    cancers_w_possible_immunosuppression:
    HIV/AIDS:
    tuberculosis:
    chronic_neurological:
    sickle_cell: 0.