male:
  0-5:
    cardiovascular: 0.001
    chronic_kidney: 0.001
    chronic respiratory: 0.009
    chronic_liver disease: 0.002
    diabetes_mellitus: 0.
    cancers_w_direct_immunosuppression: 0.004
    cancers_w_possible_immunosuppression: 0.001
    HIV/AIDS: 0.
    tuberculosis: 0.
    chronic_neurological: 0.004
    sickle_cell: 0.
  5-9:
    cardiovascular: 0.002
    chronic_kidney: 0.002
    chronic respiratory: 0.016
    chronic_liver disease: 0.002
    diabetes_mellitus: 0.001
    cancers_w_direct_immunosuppression: 0.006
    cancers_w_possible_immunosuppression: 0.
    HIV/AIDS: 0.
    tuberculosis: 0. 
    chronic_neurological: 0.005
    sickle_cell: 0.
  10-14:
    cardiovascular: 0.001
    chronic_kidney: 0.004
    chronic respiratory:0.016
    chronic_liver disease: 0.003
    diabetes_mellitus: 0.004
    cancers_w_direct_immunosuppression: 0.003
    cancers_w_possible_immunosuppression: 0.
    HIV/AIDS: 0.
    tuberculosis: 0.
    chronic_neurological: 0.005
    sickle_cell: 0.
  15-19:
    cardiovascular: 0.002
    chronic_kidney: 0.007
    chronic respiratory: 0.019
    chronic_liver disease: 0.004
    diabetes_mellitus: 0.014
    cancers_w_direct_immunosuppression: 0.003
    cancers_w_possible_immunosuppression: 0.001
    HIV/AIDS: 0.
    tuberculosis: 0.
    chronic_neurological: 0.005
    sickle_cell: 0.
  20-24:
    cardiovascular: 0.003
    chronic_kidney: 0.012
    chronic respiratory: 0.026
    chronic_liver disease: 0.006
    diabetes_mellitus: 0.034
    cancers_w_direct_immunosuppression: 0.003
    cancers_w_possible_immunosuppression: 0.002
    HIV/AIDS: 0.
    tuberculosis: 0.
    chronic_neurological: 0.005
    sickle_cell: 0.
  25-29:
    cardiovascular: 0.007
    chronic_kidney: 0.021
    chronic respiratory: 0.03
    chronic_liver disease: 0.011
    diabetes_mellitus: 0.046
    cancers_w_direct_immunosuppression: 0.005
    cancers_w_possible_immunosuppression: 0.004
    HIV/AIDS: 0.001
    tuberculosis: 0.
    chronic_neurological: 0.005
    sickle_cell: 0.
  30-34:
    cardiovascular: 0.011
    chronic_kidney: 0.029
    chronic respiratory: 0.035
    chronic_liver disease: 0.021
    diabetes_mellitus: 0.051
    cancers_w_direct_immunosuppression: 0.008
    cancers_w_possible_immunosuppression: 0.006
    HIV/AIDS: 0.003
    tuberculosis: 0.
    chronic_neurological: 0.006
    sickle_cell: 0.
  35-39:
    cardiovascular: 0.018
    chronic_kidney: 0.036
    chronic respiratory: 0.043
    chronic_liver disease: 0.031
    diabetes_mellitus: 0.056
    cancers_w_direct_immunosuppression: 0.008
    cancers_w_possible_immunosuppression: 0.006
    HIV/AIDS: 0.004
    tuberculosis: 0.
    chronic_neurological:0.006
    sickle_cell: 0.
  40-44:
    cardiovascular: 0.042
    chronic_kidney: 0.042
    chronic respiratory: 0.056
    chronic_liver disease: 0.034
    diabetes_mellitus: 0.064
    cancers_w_direct_immunosuppression: 0.008
    cancers_w_possible_immunosuppression: 0.009
    HIV/AIDS: 0.004
    tuberculosis: 0.
    chronic_neurological: 0.006
    sickle_cell: 0.
  45-49:
    cardiovascular:	0.064
    chronic_kidney:	0.048
    chronic respiratory:	0.074
    chronic_liver disease:	0.033
    diabetes_mellitus:	0.086
    cancers_w_direct_immunosuppression:	0.012
    cancers_w_possible_immunosuppression:	0.012
    HIV/AIDS:	0.004
    tuberculosis:	0.000
    chronic_neurological:	0.006
    sickle_cell:	0.000
  50-54:
    cardiovascular:	0.102
    chronic_kidney:	0.057
    chronic respiratory:	0.099
    chronic_liver disease:	0.032
    diabetes_mellitus:	0.120
    cancers_w_direct_immunosuppression:	0.011
    cancers_w_possible_immunosuppression:	0.020
    HIV/AIDS:	0.003
    tuberculosis:	0.000
    chronic_neurological:	0.007
    sickle_cell:	0.000
  55-59:
    cardiovascular:	0.163
    chronic_kidney:	0.074
    chronic respiratory:	0.144
    chronic_liver disease:	0.031
    diabetes_mellitus:	0.155
    cancers_w_direct_immunosuppression:	0.014
    cancers_w_possible_immunosuppression:	0.034
    HIV/AIDS:	0.003
    tuberculosis:	0.000
    chronic_neurological:	0.009
    sickle_cell:	0.000
  60-64:
    cardiovascular:	0.247
    chronic_kidney:	0.100
    chronic respiratory:	0.182
    chronic_liver disease:	0.029
    diabetes_mellitus:	0.188
    cancers_w_direct_immunosuppression:	0.019
    cancers_w_possible_immunosuppression:	0.058
    HIV/AIDS:	0.003
    tuberculosis:	0.000
    chronic_neurological:	0.013
    sickle_cell:	0.000
  65-69:
    cardiovascular:	0.341
    chronic_kidney:	0.138
    chronic respiratory:	0.225
    chronic_liver disease:	0.026
    diabetes_mellitus:	0.212
    cancers_w_direct_immunosuppression:	0.024
    cancers_w_possible_immunosuppression:	0.088
    HIV/AIDS:	0.003
    tuberculosis:	0.000
    chronic_neurological:	0.021
    sickle_cell:	0.000
  70-74:
    cardiovascular:	0.440
    chronic_kidney:	0.191
    chronic respiratory:	0.272
    chronic_liver disease:	0.024
    diabetes_mellitus:	0.238
    cancers_w_direct_immunosuppression:	0.030
    cancers_w_possible_immunosuppression:	0.107
    HIV/AIDS:	0.002
    tuberculosis:	0.000
    chronic_neurological:	0.037
    sickle_cell:	0.000
  75-79:
    cardiovascular:	0.521
    chronic_kidney:	0.263
    chronic respiratory:	0.320
    chronic_liver disease:	0.022
    diabetes_mellitus:	0.293
    cancers_w_direct_immunosuppression:	0.040
    cancers_w_possible_immunosuppression:	0.131
    HIV/AIDS:	0.001
    tuberculosis:	0.000
    chronic_neurological:	0.071
    sickle_cell:	0.000
  80-84:
    cardiovascular:	0.574
    chronic_kidney:	0.347
    chronic respiratory:	0.358
    chronic_liver disease:	0.019
    diabetes_mellitus:	0.364
    cancers_w_direct_immunosuppression:	0.042
    cancers_w_possible_immunosuppression:	0.100
    HIV/AIDS:	0.000
    tuberculosis:	0.000
    chronic_neurological:	0.129
    sickle_cell:	0.000
  85-89:
    cardiovascular:	0.592
    chronic_kidney:	0.427
    chronic respiratory:	0.391
    chronic_liver disease:	0.016
    diabetes_mellitus:	0.399
    cancers_w_direct_immunosuppression:	0.051
    cancers_w_possible_immunosuppression:	0.138
    HIV/AIDS:	0.000
    tuberculosis:	0.000
    chronic_neurological:	0.205
    sickle_cell:	0.000
  90-94:
    cardiovascular:	0.580
    chronic_kidney:	0.496
    chronic respiratory:	0.435
    chronic_liver disease:	0.014
    diabetes_mellitus:	0.396
    cancers_w_direct_immunosuppression:	0.051
    cancers_w_possible_immunosuppression:	0.150
    HIV/AIDS:	0.000
    tuberculosis:	0.000
    chronic_neurological:	0.276
    sickle_cell:	0.000
  95-100:
    cardiovascular:	0.540
    chronic_kidney:	0.562
    chronic respiratory:	0.507
    chronic_liver disease:	0.018
    diabetes_mellitus:	0.383
    cancers_w_direct_immunosuppression:	0.019
    cancers_w_possible_immunosuppression:	0.069
    HIV/AIDS:	0.000
    tuberculosis:	0.000
    chronic_neurological:	0.322
    sickle_cell:	0.000

female:
  0-5:
    cardiovascular:	0.000
    chronic_kidney:	0.001
    chronic respiratory:	0.008
    chronic_liver disease:	0.002
    diabetes_mellitus:	0.000
    cancers_w_direct_immunosuppression:	0.004
    cancers_w_possible_immunosuppression:	0.001
    HIV/AIDS:	0.000
    tuberculosis:	0.000
    chronic_neurological:	0.005
    sickle_cell:	0.000
  5-9:
    cardiovascular:	0.000
    chronic_kidney:	0.002
    chronic respiratory:	0.015
    chronic_liver disease:	0.002
    diabetes_mellitus:	0.001
    cancers_w_direct_immunosuppression:	0.004
    cancers_w_possible_immunosuppression:	0.000
    HIV/AIDS:	0.000
    tuberculosis:	0.000
    chronic_neurological:	0.006
    sickle_cell:	0.000
  10-14:
    cardiovascular:	0.002
    chronic_kidney:	0.004
    chronic respiratory:	0.016
    chronic_liver disease:	0.003
    diabetes_mellitus:	0.006
    cancers_w_direct_immunosuppression:	0.002
    cancers_w_possible_immunosuppression:	0.000
    HIV/AIDS:	0.000
    tuberculosis:	0.000
    chronic_neurological:	0.006
    sickle_cell:	0.000
  15-19:
    cardiovascular:	0.007
    chronic_kidney:	0.009
    chronic respiratory:	0.022
    chronic_liver disease:	0.005
    diabetes_mellitus:	0.021
    cancers_w_direct_immunosuppression:	0.002
    cancers_w_possible_immunosuppression:	0.001
    HIV/AIDS:	0.000
    tuberculosis:	0.000
    chronic_neurological:	0.006
    sickle_cell:	0.000
  20-24:
    cardiovascular:	0.009
    chronic_kidney:	0.018
    chronic respiratory:	0.032
    chronic_liver disease:	0.007
    diabetes_mellitus:	0.037
    cancers_w_direct_immunosuppression:	0.002
    cancers_w_possible_immunosuppression:	0.002
    HIV/AIDS:	0.001
    tuberculosis:	0.000
    chronic_neurological:	0.006
    sickle_cell:	0.000
  25-29:
    cardiovascular:	0.016
    chronic_kidney:	0.033
    chronic respiratory:	0.037
    chronic_liver disease:	0.010
    diabetes_mellitus:	0.044
    cancers_w_direct_immunosuppression:	0.005
    cancers_w_possible_immunosuppression:	0.006
    HIV/AIDS:	0.001
    tuberculosis:	0.000
    chronic_neurological:	0.007
    sickle_cell:	0.000
  30-34:
    cardiovascular:	0.020
    chronic_kidney:	0.046
    chronic respiratory:	0.044
    chronic_liver disease:	0.017
    diabetes_mellitus:	0.047
    cancers_w_direct_immunosuppression:	0.007
    cancers_w_possible_immunosuppression:	0.011
    HIV/AIDS:	0.002
    tuberculosis:	0.000
    chronic_neurological:	0.008
    sickle_cell:	0.000
  35-39:
    cardiovascular:	0.022
    chronic_kidney:	0.054
    chronic respiratory:	0.055
    chronic_liver disease:	0.020
    diabetes_mellitus:	0.050
    cancers_w_direct_immunosuppression:	0.006
    cancers_w_possible_immunosuppression:	0.015
    HIV/AIDS:	0.002
    tuberculosis:	0.000
    chronic_neurological:	0.008
    sickle_cell:	0.000
  40-44:
    cardiovascular:	0.049
    chronic_kidney:	0.059
    chronic respiratory:	0.071
    chronic_liver disease:	0.021
    diabetes_mellitus:	0.056
    cancers_w_direct_immunosuppression:	0.007
    cancers_w_possible_immunosuppression:	0.023
    HIV/AIDS:	0.002
    tuberculosis:	0.000
    chronic_neurological:	0.008
    sickle_cell:	0.000
  45-49:
    cardiovascular:	0.064
    chronic_kidney:	0.066
    chronic respiratory:	0.091
    chronic_liver disease:	0.021
    diabetes_mellitus:	0.070
    cancers_w_direct_immunosuppression:	0.008
    cancers_w_possible_immunosuppression:	0.032
    HIV/AIDS:	0.002
    tuberculosis:	0.000
    chronic_neurological:	0.009
    sickle_cell:	0.000
  50-54:
    cardiovascular:	0.081
    chronic_kidney:	0.077
    chronic respiratory:	0.114
    chronic_liver disease:	0.021
    diabetes_mellitus:	0.092
    cancers_w_direct_immunosuppression:	0.008
    cancers_w_possible_immunosuppression:	0.042
    HIV/AIDS:	0.001
    tuberculosis:	0.000
    chronic_neurological:	0.009
    sickle_cell:	0.000
  55-59:
    cardiovascular:	0.112
    chronic_kidney:	0.098
    chronic respiratory:	0.157
    chronic_liver disease:	0.020
    diabetes_mellitus:	0.116
    cancers_w_direct_immunosuppression:	0.010
    cancers_w_possible_immunosuppression:	0.053
    HIV/AIDS:	0.001
    tuberculosis:	0.000
    chronic_neurological:	0.011
    sickle_cell:	0.000
  60-64:
    cardiovascular:	0.160
    chronic_kidney:	0.131
    chronic respiratory:	0.188
    chronic_liver disease:	0.019
    diabetes_mellitus:	0.138
    cancers_w_direct_immunosuppression:	0.012
    cancers_w_possible_immunosuppression:	0.064
    HIV/AIDS:	0.001
    tuberculosis:	0.000
    chronic_neurological:	0.014
    sickle_cell:	0.000
  65-69:
    cardiovascular:	0.229
    chronic_kidney:	0.179
    chronic respiratory:	0.226
    chronic_liver disease:	0.017
    diabetes_mellitus:	0.158
    cancers_w_direct_immunosuppression:	0.015
    cancers_w_possible_immunosuppression:	0.076
    HIV/AIDS:	0.001
    tuberculosis:	0.000
    chronic_neurological:	0.021
    sickle_cell:	0.000
  70-74:
    cardiovascular:	0.309
    chronic_kidney:	0.252
    chronic respiratory:	0.268
    chronic_liver disease:	0.016
    diabetes_mellitus:	0.183
    cancers_w_direct_immunosuppression:	0.019
    cancers_w_possible_immunosuppression:	0.081
    HIV/AIDS:	0.001
    tuberculosis:	0.000
    chronic_neurological:	0.038
    sickle_cell:	0.000
  75-79:
    cardiovascular:	0.393
    chronic_kidney:	0.360
    chronic respiratory:	0.306
    chronic_liver disease:	0.014
    diabetes_mellitus:	0.232
    cancers_w_direct_immunosuppression:	0.023
    cancers_w_possible_immunosuppression:	0.090
    HIV/AIDS:	0.001
    tuberculosis:	0.000
    chronic_neurological:	0.073
    sickle_cell:	0.000
  80-84:
    cardiovascular:	0.451
    chronic_kidney:	0.482
    chronic respiratory:	0.331
    chronic_liver disease:	0.012
    diabetes_mellitus:	0.294
    cancers_w_direct_immunosuppression:	0.023
    cancers_w_possible_immunosuppression:	0.079
    HIV/AIDS:	0.000
    tuberculosis:	0.000
    chronic_neurological:	0.137
    sickle_cell:	0.000
  85-89:
    cardiovascular:	0.483
    chronic_kidney:	0.585
    chronic respiratory:	0.350
    chronic_liver disease:	0.010
    diabetes_mellitus:	0.325
    cancers_w_direct_immunosuppression:	0.029
    cancers_w_possible_immunosuppression:	0.099
    HIV/AIDS:	0.000
    tuberculosis:	0.000
    chronic_neurological:	0.224
    sickle_cell:	0.000
  90-94:
    cardiovascular:	0.485
    chronic_kidney:	0.674
    chronic respiratory:	0.378
    chronic_liver disease:	0.007
    diabetes_mellitus:	0.324
    cancers_w_direct_immunosuppression:	0.030
    cancers_w_possible_immunosuppression:	0.108
    HIV/AIDS:	0.000
    tuberculosis:	0.000
    chronic_neurological:	0.311
    sickle_cell:	0.000
  95-100:
    cardiovascular:	0.454
    chronic_kidney:	0.757
    chronic respiratory:	0.434
    chronic_liver disease:	0.005
    diabetes_mellitus:	0.313
    cancers_w_direct_immunosuppression:	0.009
    cancers_w_possible_immunosuppression:	0.057
    HIV/AIDS:	0.000
    tuberculosis:	0.000
    chronic_neurological:	0.373
    sickle_cell:	0.000