poisson_parameters:
  male:
    0-75: 2.0
    75-120: 3.0
  female:
    0-75: 2.0
    75-120: 3.0
weekend_boost: 0.5
drags_household_probability: 0.5
# source
#https://www.ageuk.org.uk/globalassets/age-uk/documents/reports-and-publications/reports-and-briefings/health--wellbeing/rb_june15_lonelines_in_later_life_evidence_review.pdf
# 17 % of the old people have less than weekly contact
# 11 % less than monthly
# we assume that each person with a relative in a households has
# a 7% probability of visiting a relative there.
# This gives a weekly probability of 38% and 89% monthly
# assuming 3 hours of leisure a day, we have
# 1 - exp(-lambda * 3 hours * 7 days a week) = 0.38
# -> lambda = 1/21 * - log(1-0.38) = 0.0227 / hour -> 0.54 / day
