social distancing:
  alpha factor: 1.0
  beta factor:
    box: 0.5
    pub: 0.5
    grocery: 0.5
    cinema: 0.5
    commute_unit: 0.5
    commute_city_unit: 0.5
    hospital: 0.5
    care_home: 0.5
    company: 0.5
    school: 0.5
    household: 1.0
    university: 0.5

company_closure:
  sectors:
    A:
    # Agriculture, forestry and fishing
      key_worker: 1.
      furlough: 0.
    B:
    # Mining and quarrying
      key_worker: 1.
      furlough: 0.
    C:
    # Manufacturing
    # Key workers defiend as those in food, beverage, petroleum and pharmaceutical products
      key_worker: 0.177
      furlough: 0.
    D:
    # Electricity, gas, steam and air conditioning supply
      key_worker: 1.
      furlough: 0.
    E:
    # Water supply, sewerage, waste management and remediation activities
      key_worker: 1.
      furlough: 0.
    F:
    # Construction
      furlough: 0.
    G:
    # Wholesale and retrail trade, repair of motor vehicles and motorcycles
      key_worker: 0.223
      furlough: 0.0680
    H:
    # Transport and storage
    # Assume all not furloughed are key
      key_worker: 0.758
      furlough: 0.242
    I:
    # Accommodation and food service activities
      furlough: 1.
    J:
    # Information and communication
    # Key workers assumed to be those working in TV and newspapers
      key_worker: 0.267
      furlough: 0.
    K:
    # Financial and insurance activities
    # Assume can work from home
      furlough: 0.
    L:
    # Real estate activities
    # Assume can work from home
      furlough: 0.
    M:
    # Professional, scientific and technical activities
    # Assume legal and lab workers go into work
      key_worker: 0.0909
      furlough: 0.
    N:
    # Assume all can work from home
      furlough: 0.0919
    O:
      key_worker: 1.
      furlough: 0.
    P:
    # Education
    # Key workers assigned by distributor separately
      furlough: 0.0833
    Q:
    # Human health and social work
    # Key workers assigned by distributor separately
      furlough: 0.0769
    R:
    # Arts, enterntainment and recreation
      furlough: 0.912
    S:
    # Other service activities
    # Key workers are funeral workers
      key_worker: 0.0526
      furlough: 0.211
    T:
    # Activities of households as employers, undifferentiated good-and services-producing activities of households for own use
    # Assume can work from home
      furlough: 0.25
    U:
    # Activities of extraterritorial organisations and bodies
    # Assume can work from home
      furlough: 0.