age_range: [0,19] # numbers correspond to age groups defined by NOMIS dataset.
mandatory_age_range: [5,18]
neighbour_schools: 35 
sector: 'P'       # NOMIS name convention
sub_sector:
  teacher_secondary:
    sector_id: 2314
    nr_of_clients: 30  # how many this job gives service to
  teacher_primary:
    sector_id: 2315
    nr_of_clients: 30
  teacher_special:
    sector_id: 2316
    nr_of_clients: 40
