interaction:
  type: collective
  parameters:
    mode: probabilistic

households:
  same_sex_couple_ratio: 0.1

schools:
  school_age_range: [1,6] # numbers correspond to age groups defined by NOMIS dataset.
  neighbour_schools: 6

companies:
  work_age_range: [8,13] # numbers correspond to age groups defined by NOMIS dataset.

people:
  adult_threshold: 6 # 18 yo
  student_age_group: 7
  old_threshold: 12 # 12 corresponds to +65 yo
