hobbies:
  sports:
    probability:
      male:
        "0-4": 0.3
        "5-9": 0.5
        "10-14": 0.7
        "15-19": 0.8
        "20-29": 0.7
        "30-39": 0.6
        "40-49": 0.5
        "50-59": 0.4
        "60+": 0.3
      female:
        "0-4": 0.2
        "5-9": 0.4
        "10-14": 0.6
        "15-19": 0.7
        "20-29": 0.6
        "30-39": 0.5
        "40-49": 0.4
        "50-59": 0.3
        "60+": 0.2
    options:
      basketball: 0.2
      football: 0.3
      swimming: 0.25
      tennis: 0.15
      running: 0.1

  art:
    probability:
      male:
        "0-4": 0.3
        "5-9": 0.4
        "10-14": 0.5
        "15-19": 0.5
        "20-29": 0.4
        "30-39": 0.5
        "40-49": 0.6
        "50-59": 0.6
        "60+": 0.5
      female:
        "0-4": 0.4
        "5-9": 0.5
        "10-14": 0.6
        "15-19": 0.7
        "20-29": 0.6
        "30-39": 0.7
        "40-49": 0.7
        "50-59": 0.6
        "60+": 0.5
    probability:
      painting: 0.15
      drawing: 0.15
      photography: 0.2
      watching films: 0.25
      reading: 0.25

  gaming:
    probability:
      male:
        "0-4": 0.2
        "5-9": 0.6
        "10-14": 0.8
        "15-19": 0.9
        "20-29": 0.7
        "30-39": 0.5
        "40-49": 0.4
        "50-59": 0.3
        "60+": 0.0
      female:
        "0-4": 0.1
        "5-9": 0.4
        "10-14": 0.6
        "15-19": 0.7
        "20-29": 0.5
        "30-39": 0.4
        "40-49": 0.3
        "50-59": 0.2
        "60+": 0.0
    options:
      video games: 0.5
      tabletop games: 0.2
      card games: 0.2
      board games: 0.1

  outdoor:
    probability:
      male:
        "0-4": 0.2
        "5-9": 0.4
        "10-14": 0.5
        "15-19": 0.7
        "20-29": 0.8
        "30-39": 0.7
        "40-49": 0.6
        "50-59": 0.5
        "60+": 0.4
      female:
        "0-4": 0.2
        "5-9": 0.3
        "10-14": 0.4
        "15-19": 0.6
        "20-29": 0.7
        "30-39": 0.7
        "40-49": 0.6
        "50-59": 0.5
        "60+": 0.5
    options:
      hiking: 0.4
      camping: 0.3
      fishing: 0.2
      gardening: 0.1

  music:
    probability:
      male:
        "0-4": 0.3
        "5-9": 0.4
        "10-14": 0.5
        "15-19": 0.6
        "20-29": 0.7
        "30-39": 0.7
        "40-49": 0.6
        "50-59": 0.5
        "60+": 0.4
      female:
        "0-4": 0.4
        "5-9": 0.5
        "10-14": 0.6
        "15-19": 0.7
        "20-29": 0.8
        "30-39": 0.7
        "40-49": 0.6
        "50-59": 0.5
        "60+": 0.4
    options:
      singing: 0.3
      playing guitar: 0.25
      playing piano: 0.2
      music production: 0.15
      songwriting: 0.1