CODECOV_TOKEN="453a1f8a-d0fd-4f4d-b812-5649b3f7ae93"
language: python
python: 
  - '3.6'

branches:
  only:
    - master
    - gh-pages


install: 
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -e .
  - bash get_data.sh

script:
  - cd test_covid
  - pytest

after_install: 
  - codecov

