language: python
python: 
  - '3.6'

branches:
  only:
    - master
    - gh-pages


install: 
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -e .
  - bash get_data.sh

script:
  - pytest --cov=covid test_covid/

after_build:
  - codecov

