language: python
python: 
  - '3.6'
  - '3.7'
  - '3.8'

install: 
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -e .
  - bash get_data.sh

script:
  - cd test_covid
  - pytest

