trajectories:
  - symptom_tag: asymptomatic
    stages:
      - symptom_tag: infected
        variation_type:
          type: constant
        completion_time: 5.1


      - symptom_tag: asymptomatic
        variation_type:
          type: constant
        completion_time: 14.


      - symptom_tag: recovered
        variation_type:
          type: constant
        completion_time: 0.0


  - symptom_tag: influenza
    stages:
      - symptom_tag: infected
        variation_type:
          type: constant
        completion_time: 5.1


      - symptom_tag: influenza
        variation_type:
          type: constant
        completion_time: 20.


      - symptom_tag: recovered
        variation_type:
          type: constant
        completion_time: 0.0


  - symptom_tag: pneumonia
    stages:
      - symptom_tag: infected
        variation_type:
          type: constant
        completion_time: 5.1


      - symptom_tag: influenza
        variation_type:
          type: constant
        completion_time: 5.


      - symptom_tag: pneumonia
        variation_type:
          type: constant
        completion_time: 20.


      - symptom_tag: recovered
        variation_type:
          type: constant
        completion_time: 0.0


  - symptom_tag: hospitalised
    stages:
      - symptom_tag: infected
        variation_type:
          type: constant
        completion_time: 5.1


      - symptom_tag: influenza
        variation_type:
          type: constant
        completion_time: 2.


      - symptom_tag: hospitalised
        variation_type:
          type: constant
        completion_time: 20.


      - symptom_tag: recovered
        variation_type:
          type: constant
        completion_time: 0.0


  - symptom_tag: intensive_care
    stages:
      - symptom_tag: infected
        variation_type:
          type: constant
        completion_time: 5.1


      - symptom_tag: influenza
        variation_type:
          type: constant
        completion_time: 2.


      - symptom_tag: hospitalised
        variation_type:
          type: constant
        completion_time: 2.


      - symptom_tag: intensive_care
        variation_type:
          type: constant
        completion_time: 20.


      - symptom_tag: hospitalised
        variation_type:
          type: constant
        completion_time: 20.


      - symptom_tag: recovered
        variation_type:
          type: constant
        completion_time: 0.0


  - symptom_tag: dead
    stages:
      - symptom_tag: infected
        variation_type:
          type: constant
        completion_time: 5.1


      - symptom_tag: influenza
        variation_type:
          type: constant
        completion_time: 2.


      - symptom_tag: hospitalised
        variation_type:
          type: constant
        completion_time: 2.


      - symptom_tag: intensive_care
        variation_type:
          type: constant
        completion_time: 10.


      - symptom_tag: dead
        variation_type:
          type: constant
        completion_time: 0.
