trajectories:

  - stages:
      - symptom_tag: exposed
        completion_time:
          type: beta
          a: 2.29
          b: 19.05
          loc: 0.39
          scale: 39.8 

      - symptom_tag: asymptomatic
        completion_time:
          type: constant
          value: 14.


      - symptom_tag: recovered
        completion_time:
          type: constant
          value: 0.0


  - stages:
      - symptom_tag: exposed
        completion_time:
          type: beta
          a: 2.29
          b: 19.05
          loc: 0.39
          scale: 39.8

      - symptom_tag: influenza
        completion_time:
          type: constant
          value: 20.


      - symptom_tag: recovered
        completion_time:
          type: constant
          value: 0.0


  - stages:
      - symptom_tag: exposed
        completion_time:
          type: beta
          a: 2.29
          b: 19.05
          loc: 0.39
          scale: 39.8
 

      - symptom_tag: influenza
        completion_time:
          type: constant
          value: 5.


      - symptom_tag: pneumonia
        completion_time:
          type: constant
          value: 20.


      - symptom_tag: recovered
        completion_time:
          type: constant
          value: 0.0


  - stages:
      
      - symptom_tag: exposed
        completion_time:
          type: beta
          a: 2.29
          b: 19.05
          loc: 0.39
          scale: 39.8

      - symptom_tag: influenza
        completion_time:
          type: exponential
          loc: 1
          scale: 4.12


      - symptom_tag: hospitalised
        completion_time:
          type: beta
          a: 1.35
          b: 3.68
          loc: 0.05
          scale: 27.1


      - symptom_tag: recovered
        completion_time:
          type: constant
          value: 0.0


  - stages:
      
      - symptom_tag: exposed
        completion_time:
          type: beta
          a: 2.29
          b: 19.05
          loc: 0.39
          scale: 39.8

      - symptom_tag: influenza
        completion_time:
          type: exponential
          loc: 1
          scale: 4.12


      - symptom_tag: hospitalised
        completion_time:
          type: constant
          value: 0.0


      - symptom_tag: intensive_care
        completion_time:
          type: beta
          a: 1.35
          b: 3.68
          loc: 0.05
          scale: 27.1


      - symptom_tag: hospitalised
        completion_time:
          type: constant
          value: 0.0


      - symptom_tag: recovered
        completion_time:
          type: constant
          value: 0.0


  - stages:
      - symptom_tag: exposed
        completion_time:
          type: beta
          a: 2.29
          b: 19.05
          loc: 0.39
          scale: 39.8

      - symptom_tag: influenza
        completion_time:
          type: exponential
          loc: 1
          scale: 4.12
      
      - symptom_tag: intensive_care
        completion_time:
          type: beta
          a: 1.21
          b: 1.97
          loc: 0.08
          scale: 22.9

      - symptom_tag: dead
        completion_time:
          type: constant
          value: 0.
