regional_compliance:
  1:
    start_time: 1000-07-04
    end_time: 9999-12-01
    London: 1.15
    South East: 0.99
    South West: 0.99
    West Midlands: 1.
    East Midlands: 1.
    East of England: 1.
    North West: 0.95
    North East: 0.95
    Yorkshire and The Humber: 0.95