title: Covid configuration for testing

logger:
  save_path: results

world:
  zone: test # NorthEast # available are all UK regions, and EnglandWales together.

time:
  total_days: 20
  step_duration: 
      weekday:
          1: 8
          2: 16 
      weekend:
          1: 24
  step_active_groups:
      weekday:
          1: ['schools', 'households'] # active groups during first time step
          2: ['households'] 
      weekend:
          1: ['households'] 

interaction:
  type: collective
  parameters:
    mode: probabilistic 

infection:
  asymptomatic_ratio: 0.4
  transmission:
    type: constant
    parameters:
      probability: 0.2

