title: Covid configuration for testing

logger:
  save_path: results

world:
  zone: test # NorthEast # available are all UK regions, and EnglandWales together.

time:
  total_days: 7
  step_duration: 
      weekday:
          1: 8
          2: 16 
      weekend:
          1: 24
  step_active_groups:
      weekday:
        #1: ['companies', 'schools','households'] # active groups during first time step
          1: ['schools','carehomes','households'] # active groups during first time step
          2: ['carehomes', 'households'] 
          #2: ['pubs', 'households'] 
      weekend:
          1: ['carehomes', 'households'] 

interaction:
  type: collective
  parameters:
    mode: probabilistic 

infection:
  asymptomatic_ratio: 0.4
  transmission:
    type: constant
    parameters:
      probability: 0.2
