type:
        'gamma'
max_infectiousness:
        type: lognormal
        s: 0.5 
        loc: 0.0
        scale: 1. 
shape:
        type: normal 
        loc: 1.56
        scale: 0.08
rate:
        type: normal 
        loc: 0.53
        scale: 0.03
shift:
        type: normal 
        loc: -2.12
        scale: 0.1
asymptomatic_infectious_factor:
        type: constant
        value: 0.5
mild_infectious_factor:
        type: constant
        value: 1.

