type:
        "xnexp"
max_probability:
        type: lognormal
        s: 0.5 
        loc: 0.0
        scale: 1. 
norm_time:       
        type: constant
        value: 1.
alpha:       
        type: constant
        value: 1.5

smearing_time_first_infectious:
        type: normal
        loc: -2.
        scale: 0.5
smearing_peak_position:
        type: normal
        loc: -0.7
        scale: 0.4
asymptomatic_infectious_factor:
        type: constant
        value: 0.33
mild_infectious_factor:
        type: constant
        value: 0.72

