# seats per passenger
# data from TAble RAI0201 of the Depatment of Transport statistics (2018)
seats_per_passenger:
  Birmingham: 1.14
  "Brighton and Hove": 2.34
  Bristol: 1.64
  Cambridge: 2.04
  Cardiff: 1.64
  Leeds: 1.13
  Leicester: 1.79
  Liverpool: 1.5
  London: 1.00
  Manchester: 1.37
  "Newcastle upon Tyne": 2.28
  Nottingham: 1.55
  Reading: 1.98
  Sheffield: 1.63

