disease_name: measles

susceptibilities:
  0-13 : 1
  13-100: 1.0

alpha_physical: 2.

betas:
 pub: 0.42941
 gym: 0.42941 
 grocery: 0.04137
 cinema: 0.157461
 city_transport: 0.107969 
 inter_city_transport: 0.3830 
 hospital: 0.1168
 care_home: 0.28
 company: 0.371
 school: 0.070 
 household: 0.208 
 household_visits: 0.208
 care_visits: 0.208
 university: 0.306

contact_matrices:
  # number 10 comes from the fact that on average there are 10 medics per patient
  # for ICU that should be lower, but it isn't reflected in hospital distributor yet
  hospital:
    contacts: [[5.00, 10., 10.], [1., 0., 0.], [1., 0., 0.]]
    proportion_physical: [[0.05, 1., 1.], [1.0, 0., 0.], [1., 0., 0.]]
    characteristic_time: 8 # in hours
    type: Discrete
    bins: ["workers", "patients", "icu_patients"]
  
  care_home:
    # note, visitors contacts are multiplied by ~4 because they only stay 1/4th of the characteristic time.
    contacts: [[15.00, 15.0, 5], [1.5, 4, 1], [1, 20, 0]]
    proportion_physical: [[0.05, 1., 0.], [1.0, 0.0, 0.1],[0., 0.1, 0.]]
    characteristic_time: 24 
    type: Discrete
    bins: ["workers", "residents", "visitors"]
  
  company:
    contacts: [[4.8]]
    proportion_physical: [[0.07]]
    characteristic_time: 8
    type: Age
    bins: [0,100]
  
  
  university:
    contacts: [[2, 0.75, 0.75, 0.75, 0.75, 0.75], [0.75, 2, 0.75, 0.75, 0.75, 0.75], [0.75, 0.75, 2, 0.75, 0.75, 0.75], [0.75, 0.75, 0.75, 2, 0.75, 0.75], [0.75, 0.75, 0.75, 0.75, 2, 0.75], [0.75, 0.75, 0.75, 0.75, 0.75, 2]]
    proportion_physical: [[0.25, 0.25, 0.25, 0.25, 0.25, 0.25], [0.25, 0.25, 0.25, 0.25, 0.25, 0.25], [0.25, 0.25, 0.25, 0.25, 0.25, 0.25], [0.25, 0.25, 0.25, 0.25, 0.25, 0.25], [0.25, 0.25, 0.25, 0.25, 0.25, 0.25], [0.25, 0.25, 0.25, 0.25, 0.25, 0.25]]
    characteristic_time: 8
    type: Discrete
    bins: ["Professors", "1", "2", "3", "4", "5"]
  
  
  school:
    contacts: [[5, 15], [0.75, 2.5]]
    proportion_physical: [[0.05, 0.08], [0.08, 0.15]]
    xi:       0.3
    characteristic_time: 8
    type: Discrete
    bins: ["teachers", "students"]
   
  household:
    contacts: [[1.2,1.27,1.27,1.27],[1.69,1.34,1.3,1.3],[1.69,1.47,1.34,1.34],[1.69,1.47,1.34,2.00]]
    proportion_physical: [[0.79,0.7,0.7,0.7],[0.7,0.34,0.4,0.4],[0.7,0.4,0.62,0.62],[0.7,0.62,0.62,0.45]] 
    characteristic_time: 12
    type: Discrete
    bins: ["kids","young adults","adults","old adults"]

  airport:
    contacts: [[8]]  # High contact rate in crowded terminal
    proportion_physical: [[0.25]]  # Higher physical contact in security/queues
    characteristic_time: 4  # Average time spent in airport (hours)
    type: Discrete
    bins: ["travelers"]
  
  aircraft:
    contacts: [[10]]  # High contact rate due to enclosed cabin
    proportion_physical: [[0.3]]  # Higher physical contact due to confined space
    characteristic_time: 3  # Average flight duration in hours
    type: Discrete
    bins: ["passengers"]
  
  pub:
    contacts: [[3]]
    proportion_physical: [[0.12]]
    characteristic_time: 3
    type: Age
    bins: [0,100]

  gym:
    contacts: [[3]]
    proportion_physical: [[0.12]]
    characteristic_time: 3
    type: Age
    bins: [0,100]

  grocery:
    contacts: [[1.5]]
    proportion_physical: [[0.12]]
    characteristic_time: 3
    type: Age
    bins: [0,100]

  cinema:
    contacts: [[3]]
    proportion_physical: [[0.12]]
    characteristic_time: 3    
    type: Age
    bins: [0,100]

  city_transport:
    contacts: [[6]]
    proportion_physical: [[0.07]]
    characteristic_time: 2
    type: Age
    bins: [0,100]

  inter_city_transport:
    contacts: [[4]]
    proportion_physical: [[0.05]]
    characteristic_time: 2
    type: Age
    bins: [0,100]


interactive_groups:
  # configuration options for specific interactive groups.
  company:
    sector_betas:
      A: 1.
      B: 0.9
      C: 1.
      D: 1.
      E: 1.
      F: 1.
      G: 0.75
      H: 0.5
      I: 1.
      J: 0.7
      K: 0.5
      L: 0.3
      M: 0.3
      N: 0.2
      O: 0.5
      P: 1.
      Q: 1.
      R: 0.7
      S: 0.8
      T: 1.
      U: 1.


