alpha_physical: 2.

beta:
 box: 1
 pub: 0.1 
 grocery: 0.1
 cinema: 0.1
 commute_unit: 0.5 
 commute_city_unit: 0.5 
 hospital: 0.5 
 care_home: 0.5 
 company: 0.5 
 school: 0.5 
 household: 0.5 

contact_matrices:
 hospital:
  # number 10 comes from the fact that on average there are 10 medics per patient
  # for ICU that should be lower, but it isn't reflected in hospital distributor yet
  contacts: [[5.00, 10., 10.], [1., 0., 0.], [1., 0., 0.]]
  proportion_physical: [[0.05, 1., 1.], [1.0, 0., 0.], [1., 0., 0.]]
 care_home:
  contacts: [[5.00, 10., 1.], [1., 0, 2.], [0.25,1,0]]
  proportion_physical: [[0.05, 1., 0.], [1.0, 0.4, 1.],[0.,0.5,0.]]
 company:
  contacts: [[4.8]]
  proportion_physical: [[0.07]]
 school:
  contacts: [[5, 0.75], [15, 2.5]]
  proportion_physical: [[0.05, 0.08], [0.08, 0.15]]
  xi:       0.3
 household:
  contacts: [[1.20, 1.69, 1.69, 1.69], [1.27, 1.34, 1.47, 1.47], [1.27, 1.30, 1.34, 1.34], [1.27, 1.30, 1.34, 2.00]]
  proportion_physical: [[0.79, 0.7, 0.7, 0.7], [0.7, 0.34, 0.4, 0.62], [0.7, 0.4, 0.62, 0.62], [0.7, 0.4, 0.62, 0.45]]
