alpha_physical: 2.
contact_matrices:
  box:
    beta: 1
    contacts: [[1.]]
    physical: [[0.]]
  hospital:
    contacts: [[5.00, 1., 1.], [10., 0., 0.], [5., 0., 0.]]
    physical: [[0.05, 1., 1.], [1.0, 0., 0.], [1., 0., 0.]]
  care_home:
    contacts: [[5.00, 1.], [10., 2.0]]
    physical: [[0.05, 1.], [1.0, 0.4]]
  company:
    beta:     1.
    contacts: [[4.8]]
    physical: [[0.07]]
  school:
    beta:     1.
    contacts: [[25, 0.75], [15, 2.5]]
    physical: [[0.05, 0.08], [0.08, 0.15]]
    xi:       0.3
  household:
    beta:     1.
    contacts: [[1.20, 1.69, 1.69, 1.69], [1.27, 1.34, 1.47, 1.47], [1.27, 1.30, 1.34, 1.34], [1.27, 1.30, 1.34, 2.00]]
    physical: [[0.79, 0.7, 0.7, 0.7], [0.7, 0.34, 0.4, 0.62], [0.7, 0.4, 0.62, 0.62], [0.7, 0.4, 0.62, 0.45]]
   
