vaccines:
  Pfizer:
    days_administered_to_effective: [5,7,5]
    days_effective_to_waning: [1,1,1]
    days_waning: [1,1,1]
    waning_factor: 1.
    sterilisation_efficacies:
      - Covid19:
          0-100: 0.52
      - Covid19:
          0-100: 0.95
      - Covid19:
          0-100: 0.98
    symptomatic_efficacies:
      - Covid19:
          0-100: 0.52
      - Covid19:
          0-100: 0.95
      - Covid19:
          0-100: 0.98

  AstraZeneca:
    days_administered_to_effective: [5,7,5]
    days_effective_to_waning: [1,1,1]
    days_waning: [1,1,1]
    waning_factor: 1.
    sterilisation_efficacies:
      - Covid19:
          0-100: 0.32
      - Covid19:
          0-100: 0.75
      - Covid19:
          0-100: 0.88
    symptomatic_efficacies:
      - Covid19:
          0-100: 0.32
      - Covid19:
          0-100: 0.75
      - Covid19:
          0-100: 0.88
vaccination_campaigns:
  1:
    start_time: 3020-12-01
    end_time: 3020-12-20 
    days_to_next_dose: [0,14]
    group_by: 'residence'
    group_type: 'care_home'
    group_coverage: 0.3
    vaccine_type: 'Pfizer'
    dose_numbers: [0,1]
  2:
      start_time: 3020-12-01
      end_time: 3020-12-20 
      days_to_next_dose: [0,14]
      group_by: 'residence'
      group_type: 'care_home'
      group_coverage: 0.3
      vaccine_type: 'AstraZeneca'
      dose_numbers: [0,1]
  3:
      start_time: 3021-02-25 
      end_time: 3021-02-27 
      days_to_next_dose: [0]
      group_by: 'residence'
      group_type: 'care_home'
      group_coverage: 1.
      vaccine_type: 'Pfizer'
      dose_numbers: [2]
      last_dose_type: ['Pfizer', 'AstraZeneca']

