- description: Work mainly at or from home
- description: Underground, metro, light rail, tram
- description: Train
- description: Bus, minibus or coach
- description: Taxi
- description: Motorcycle, scooter or moped
- description: Driving a car or van
- description: Passenger in a car or van
- description: Bicycle
- description: On foot
- description: Other method of travel to work
- description: Not in employment