trajectories:
  - symptom_tag: asymptomatic
    stages:
      - symptom_tag: infected
        completion_time:
          type: constant
          value: 5.1


      - symptom_tag: asymptomatic
        completion_time:
          type: constant
          value: 14.


      - symptom_tag: recovered
        completion_time:
          type: constant
          value: 0.0


  - symptom_tag: influenza
    stages:
      - symptom_tag: infected
        completion_time:
          type: constant
          value: 5.1


      - symptom_tag: influenza
        completion_time:
          type: constant
          value: 20.


      - symptom_tag: recovered
        completion_time:
          type: constant
          value: 0.0


  - symptom_tag: pneumonia
    stages:
      - symptom_tag: infected
        completion_time:
          type: constant
          value: 5.1


      - symptom_tag: influenza
        completion_time:
          type: constant
          value: 5.


      - symptom_tag: pneumonia
        completion_time:
          type: constant
          value: 20.


      - symptom_tag: recovered
        completion_time:
          type: constant
          value: 0.0


  - symptom_tag: hospitalised
    stages:
      - symptom_tag: infected
        completion_time:
          type: constant
          value: 5.1


      - symptom_tag: influenza
        completion_time:
          type: constant
          value: 2.


      - symptom_tag: hospitalised
        completion_time:
          type: constant
          value: 20.


      - symptom_tag: recovered
        completion_time:
          type: constant
          value: 0.0


  - symptom_tag: intensive_care
    stages:
      - symptom_tag: infected
        completion_time:
          type: constant
          value: 5.1


      - symptom_tag: influenza
        completion_time:
          type: constant
          value: 2.


      - symptom_tag: hospitalised
        completion_time:
          type: constant
          value: 2.


      - symptom_tag: intensive_care
        completion_time:
          type: constant
          value: 20.


      - symptom_tag: hospitalised
        completion_time:
          type: constant
          value: 20.


      - symptom_tag: recovered
        completion_time:
          type: constant
          value: 0.0


  - symptom_tag: dead
    stages:
      - symptom_tag: infected
        completion_time:
          type: constant
          value: 5.1


      - symptom_tag: influenza
        completion_time:
          type: constant
          value: 2.


      - symptom_tag: hospitalised
        completion_time:
          type: constant
          value: 2.


      - symptom_tag: intensive_care
        completion_time:
          type: constant
          value: 10.


      - symptom_tag: dead
        completion_time:
          type: constant
          value: 0.
