title: SI model 

time:
  total_days: 50 
  step_duration: 
      weekday:
          1: 12 
          2: 12
      weekend:
          1: 24
  step_activities:
      weekday:
          1: ['box'] # active groups during first time step
          2: ['box'] # active groups during first time step
      weekend:
          1: ['box'] # active groups during first time step




