title: SI model 

logger:
  save_path: results

world:
  zone: test # NorthEast # available are all UK regions, and EnglandWales together.

time:
  total_days: 25 
  step_duration: 
      weekday:
          1: 12 
          2: 12
      weekend:
          1: 24
  step_active_groups:
      weekday:
          1: ['boxes'] # active groups during first time step
          2: ['boxes'] # active groups during first time step
      weekend:
          1: ['boxes'] # active groups during first time step

interaction:
  type: default 

infection:
  type: constant
  asymptomatic_ratio: 0.4
  transmission:
    type: constant
    parameters:
      probability: 0.3
  symptoms:
    type: constant
    parameters:
      recovery_rate: 0.05


