title: SI model 

logger:
  save_path: results

world:
  zone: test # NorthEast # available are all UK regions, and EnglandWales together.

time:
  total_days: 5
  step_duration: 
      weekday:
          1: 8
          2: 16
          #3: 4
          #4: 4
          #5: 4
          #6: 4
      weekend:
          1: 24
          #2: 4
          #3: 4
          #4: 4
          #5: 4
          #6: 4
  step_active_groups:
      weekday:
          1: ['boxes','hospitals'] # active groups during first time step
          2: ['boxes','hospitals'] # active groups during first time step
      weekend:
          1: ['boxes','hospitals'] # active groups during first time step

interaction:
  type: collective
  parameters:
    mode: superposition 

infection:
  type: constant
  transmission:
    type: constant
    parameters:
      transmission_probability:
        distribution: constant
        parameters:
          value: 0.05
  symptoms:
    type: constant
    parameters:
      recovery_rate: 0.05
