title: Covid configuration example

logger:
  save_path: results

world:
  zone: test # NorthEast # available are all UK regions, and EnglandWales together.

time:
  total_days: 10
  step_duration:
    weekday:
      1: 8 # first time step duration in hours
      2: 16
    weekend:
      1: 24
  step_active_groups:
    weekday:
      1: [] # active groups during first time step
      2: []
    weekend:
      1: []


people:
  adult_threshold: 6 # 18 yo
  student_age_group: 7
  old_threshold: 12 # 12 corresponds to +65 yo

households:
  same_sex_couple_ratio: 0.1

schools:
  school_age_range: [1,6] # numbers correspond to age groups defined by NOMIS dataset.
  neighbour_schools: 6

companies:
  work_age_range: [8,13] # numbers correspond to age groups defined by NOMIS dataset.

interaction:
  type: collective
  mode: probabilistic
  parameters:
    severe_treatment:
      type: constant
      omega: 2

infection:
  asymptomatic_ratio: 0.4
  transmission:
    type:         XNExp
    probability:
      mean:       0.8
    relaxation:
      mean:       2.
    mean_time:
      mean:       10.
    end_time:
      mean:       20.
