title: Covid configuration example

activity_to_groups:
  medical_facility: ["hospitals"]
  primary_activity: ['schools', 'companies', "universities"]
  #leisure: ['pubs', 'cinemas', 'groceries', "care_home_visits", "household_visits"] 
  residence: ['households', 'care_homes']

time:
  total_days: 50
  initial_day: "2020-03-01" 
  step_duration: 
      weekday:
          0: 12
          1: 8
          2: 4
      weekend:
          0: 12
          1: 12
  step_activities:
      weekday:
          0: ['medical_facility', 'residence'] 
          1: ['medical_facility', 'primary_activity','residence'] 
          2: ['medical_facility', 'residence']
      weekend:
          0: ['medical_facility', 'residence']
          1: ['medical_facility', 'residence']

