title: SI model 

time:
  total_days: 7
  initial_day: "2020-03-01" 
  step_duration: 
      weekday:
          0: 12 
          1: 12
      weekend:
          0: 24
  step_activities:
      weekday:
          0: ['box'] # active groups during first time step
          1: ['box'] # active groups during first time step
      weekend:
          0: ['box'] # active groups during first time step




