title: Configuration example

disease:
  model: "covid19"  # Options: "covid19", "measles"

features:
  friend_hangouts:
    enabled: false
  test_and_trace:
    enabled: false
  ratty_dynamics:
    enabled: false
    animations: false

time:
  total_days: 5
  initial_day: "2025-08-28 8:00" 
  step_duration: 
      weekday:
          0: 1 
          1: 8
          2: 1
          3: 3
          4: 11
      weekend:
          0: 4 
          1: 4 
          2: 4 
          3: 12 
  step_activities:
      weekday:
          0: ['medical_facility', 'residence', 'commute'] 
          1: ['medical_facility', 'primary_activity', 'leisure', 'residence'] 
          2: ['medical_facility', 'residence', 'commute'] 
          3: ['medical_facility', 'leisure', 'residence']
          4: ['medical_facility', 'residence']
      weekend:
          0: ['medical_facility', 'leisure', 'residence']
          1: ['medical_facility', 'leisure', 'residence']
          2: ['medical_facility', 'leisure', 'residence']
          3: ['medical_facility', 'residence']

checkpoint_save_dates:
  2025-09-15

activity_to_super_groups:
  medical_facility: ["hospitals"]
  primary_activity: ['schools', 'companies', "universities"]
  leisure: ['pubs', 'cinemas', 'groceries', 'gyms', "care_home_visits", "household_visits"] 
  residence: ['households', 'care_homes']
  commute: ['city_transports', 'inter_city_transports']
