# characteristic time of 3 hours
male_age_probabilities:
  7-14: 0.57
  15-24: 0.57
  25-34: 0.32
  35-44: 0.32
  45-64: 0.16
  65-100: 0.05
female_age_probabilities:
  7-14: 0.57
  15-24: 0.57
  25-34: 0.32
  35-44: 0.32
  45-64: 0.16
  65-100: 0.05
neighbours_to_consider: 5
maximum_distance: 5
weekend_boost: 1
drags_household_probability: 0.5

# 2019: 176.1 million cinema visitors per year
# (from https://www.cinemauk.org.uk/the-industry/facts-and-figures/uk-cinema-admissions-and-box-office/annual-admissions/)
# age/gender distribution from https://www.statista.com/statistics/296240/age-and-gender-of-the-cinema-audience-uk/
