male_age_probabilities:
  3-75: 0.03
  75-80: 0.01
female_age_probabilities:
  3-75: 0.03
  75-80: 0.01
neighbours_to_consider: 5
maximum_distance: 15
weekend_boost: 1
drags_household_probability: 0.5

# 2019: 176.1 million cinema visitors per year
# (from https://www.cinemauk.org.uk/the-industry/facts-and-figures/uk-cinema-admissions-and-box-office/annual-admissions/)
# age/gender distribution from https://www.statista.com/statistics/296240/age-and-gender-of-the-cinema-audience-uk/
