male_age_probabilities:
  18-65 : 0.65
  65-100 : 0.40
female_age_probabilities:
  18-65 : 0.65
  65-100 : 0.40
neighbours_to_consider: 7
maximum_distance: 10
weekend_boost: 0.60
drags_household_probability: 0.2
