male_age_probabilities:
  18-65 : 0.90
  65-100 : 0.60
female_age_probabilities:
  18-65 : 0.90
  65-100 : 0.60
neighbours_to_consider: 15
maximum_distance: 15
weekend_boost: 0.70
drags_household_probability: 0.2
