male_age_probabilities:
  18-65 : 0.70
  65-100 : 0.38
female_age_probabilities:
  18-65 : 0.70
  65-100 : 0.38
neighbours_to_consider: 15
maximum_distance: 15
weekend_boost: 0.50
drags_household_probability: 0.2
