title: Covid configuration example

activity_to_groups:
  primary_activity: ['schools']
  leisure: ['distribution_centers','communals','female_communals','pump_latrines','household_visits'] 
  residence: ['households']

time:
  total_days: 70
  step_duration: 
      weekday:
          0: 1 
          1: 8
          2: 2
          3: 2
	  4: 2
	  5: 2
          6: 7
      weekend:
          0: 3 
          1: 2 
          2: 2 
          3: 2
	  4: 2
	  5: 13
  step_activities:
      weekday:
          0: ['hospital', 'residence'] 
          1: ['hospital', 'primary_activity', 'residence'] 
          2: ['hospital', 'leisure', 'residence'] 
          3: ['hospital', 'leisure', 'residence']
	  4: ['hospital', 'leisure', 'residence']
	  5: ['hospital', 'leisure', 'residence']
          6: ['hospital', 'residence']
      weekend:
          0: ['hospital', 'residence']
          1: ['hospital', 'leisure', 'residence']
          2: ['hospital', 'leisure', 'residence']
	  3: ['hospital', 'leisure', 'residence']
	  4: ['hospital', 'leisure', 'residence']
          5: ['hospital', 'residence']