title: Covid configuration example

activity_to_groups:
  #primary_activity: ['schools']
  leisure: ['distribution_centers', 'communals', 'female_communals', 'pump_latrines', 'religiouss'] 
  residence: ['shelters']

time:
  total_days: 70
  step_duration: 
      weekday:
          0: 2 
          1: 2
          2: 2
          3: 2
          4: 2
          5: 14
      weekend:
          0: 3
          1: 2 
          2: 2 
          3: 2
          4: 2
          5: 13
  step_activities:
      weekday:
          0: ['hospital', 'residence']
          1: ['hospital', 'leisure', 'residence'] # school
          2: ['hospital', 'leisure', 'residence'] # school
          3: ['hospital', 'leisure', 'residence'] # school
          4: ['hospital', 'leisure', 'residence'] # school
          5: ['hospital', 'residence']
      weekend:
          0: ['hospital', 'residence']
          1: ['hospital', 'leisure', 'residence']
          2: ['hospital', 'leisure', 'residence']
          3: ['hospital', 'leisure', 'residence']
          4: ['hospital', 'leisure', 'residence']
          5: ['hospital', 'residence']
