title: Covid configuration example

activity_to_groups:
  primary_activity: ['learning_centers']
  leisure: ['distribution_centers', 'communals', 'female_communals', 'pump_latrines', 'religiouss', 'play_groups', 'e_vouchers', 'n_f_distribution_centers'] 
  residence: ['shelters']
  medical_facility: ['hospitals', 'isolation_units']

time:
  initial_day: '2020-05-24'
  total_days: 4 
  step_duration: 
      weekday:
          0: 2 
          1: 2
          2: 2
          3: 2
          4: 2
          5: 14
      weekend:
          0: 3
          1: 2 
          2: 2 
          3: 2
          4: 2
          5: 13
  step_activities:
      weekday:
          0: ['medical_facility', 'residence']
          1: ['medical_facility', 'leisure', 'residence'] 
          2: ['medical_facility', 'leisure', 'residence'] 
          3: ['medical_facility', 'leisure', 'residence'] 
          4: ['medical_facility', 'leisure', 'residence'] 
          5: ['medical_facility', 'residence']
      weekend:
          0: ['medical_facility', 'residence']
          1: ['medical_facility', 'leisure', 'residence']
          2: ['medical_facility', 'leisure', 'residence']
          3: ['medical_facility', 'leisure', 'residence']
          4: ['medical_facility', 'leisure', 'residence']
          5: ['medical_facility', 'residence']
