#sector_betas:
#    A: 1.
#    B: 0.9
#    C: 1.
#    D: 1.
#    E: 1.
#    F: 1.
#    G: 0.75
#    H: 0.5
#    I: 1.
#    J: 0.7
#    K: 0.5
#    L: 0.3
#    M: 0.3
#    N: 0.2
#    O: 0.5
#    P: 1.
#    Q: 1.
#    R: 0.7
#    S: 0.8
#    T: 1.
#    U: 1.
